In [88]:
import pandas as pd
import io

In [89]:
# 1. Đọc file (Pandas sẽ nhận 761 dòng, 1 cột)
df = pd.read_csv('C:/Ky_2_nam_3/Khai thác dữ liệu/Giá cà phê/Giá cà phê trang investing/arabica.csv')

# 2. Lấy tên cột gốc (chuỗi "Date,Price,Open...")
raw_col_name = df.columns[0]

# 3. Tách cột duy nhất này thành nhiều cột dựa trên dấu phẩy
df_clean = df[raw_col_name].str.split(',', expand=True)

# 4. Gán lại tên cột cho đúng (tách từ tên cột gốc)
df_clean.columns = raw_col_name.split(',')

In [90]:
df_yahoo=pd.read_csv("C:/Ky_2_nam_3/Khai thác dữ liệu/Giá cà phê/Yahoo Finance/coffee_arabica_yahoo2026-03-15.csv")

In [91]:
df_macro=pd.read_csv("C:/Ky_2_nam_3/Khai thác dữ liệu/Giá cà phê/Giá cà phê trang macrotrends/Gia_ca_phe.csv")

In [92]:
df_clean=df_clean.drop(columns=["Price","Open","High","Low","Vol.","Change %"])
df_clean.head(10)

         Date        Gia_Viet_Nam
0  03/11/2026       166447.255908
1  03/10/2026       171312.102636
2  03/09/2026  171949.16589799998
3  03/06/2026       169864.231586
4  03/05/2026       167258.063696
5  03/04/2026  165781.23522499998
6  03/03/2026       163985.875123
7  03/02/2026       164825.640332
8  02/27/2026       162595.918915
9  02/26/2026       163493.598966

In [93]:
df_yahoo=df_yahoo.drop(columns=["Close","High","Low","Open","Volume"])
df_yahoo.tail(10)

     Unnamed: 0        Date        Gia_vnd
745         745  2026-03-02  167151.025397
746         746  2026-03-03  166339.475508
747         747  2026-03-04  168513.279330
748         748  2026-03-05  169846.538597
749         749  2026-03-06  172513.074823
750         750  2026-03-09  174918.747515
751         751  2026-03-10  174223.123216
752         752  2026-03-11  169266.857578
753         753  2026-03-12  171875.422164
754         754  2026-03-13  169701.618343

In [94]:
df_macro=df_macro.drop(columns=["Value"])
df_macro.tail(10)

     Unnamed: 0        Date   Gia_Viet_Nam
772       14366  02/26/2026  162922.287899
773       14367  02/27/2026  162198.214587
774       14368  03/02/2026  164416.775216
775       14369  03/03/2026  163698.494490
776       14370  03/04/2026  168390.489555
777       14371  03/05/2026  170892.886923
778       14372  03/06/2026  170284.665341
779       14373  03/09/2026  173545.891540
780       14374  03/10/2026  173256.262215
781       14375  03/11/2026  173256.262215